import Head from 'next/head'
import Todo from '../components/todo'
// import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Header from '../components/header'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header title="Add Your ToDo List" subtitle="Make your life little easier in managing works."/>
        <div className='todo-Div'>
          <Todo />
        </div>                
      </main>
      
    </div>
  )
}
